# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            sargeant45
tagline:          'Blogger/Programmer/Videographer/Editor/12-Year-Old/etc.'
description:      'I make programs. I also make videos. I also make blog posts. I also do stuff. I also breathe air. I also got turned down by ReadWriteThink.'
url:              http://sargeant45.github.com
baseurl:          /

author:
  name:           'Ethan Arterberry'
  url:            http://twitter.com/EthanArterberry

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sargeant45/EssayMaker
